# Generated by Django 5.0.2 on 2024-07-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_returns_date_returns_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='returns',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
