# Generated by Django 5.0.2 on 2024-07-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_sales_date_alter_returns_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
