# Generated by Django 5.0.2 on 2024-07-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_alter_sales_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
    ]
