# Generated by Django 5.0.2 on 2024-07-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_remove_sales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
