# Generated by Django 5.0.2 on 2024-07-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0008_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
