# Generated by Django 5.0.2 on 2024-07-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0010_rename_product_returns_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
