# Generated by Django 5.0.2 on 2024-07-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0012_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='quantity_returned',
            field=models.IntegerField(default=0),
        ),
    ]
