# Generated by Django 5.0.2 on 2024-07-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0013_alter_returns_quantity_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='quantity_returned',
            field=models.BigIntegerField(default=0),
        ),
    ]
